import {
  BadRequestException,
  Body,
  Controller,
  Delete,
  ForbiddenException,
  NotFoundException,
  Param,
  Post,
  Put,
  UseGuards,
} from '@nestjs/common';
import { Throttle } from '@nestjs/throttler';
import { IsOptional, IsString, MaxLength, MinLength } from 'class-validator';
import { JwtAuthGuard } from '../common/jwt-auth.guard';
import { CurrentUser } from '../common/current-user.decorator';
import { PrismaService } from '../prisma/prisma.service';
import { QueueService } from '../queue/queue.service';
import { AuditService } from '../audit/audit.service';
import { ModerationService } from '../moderation/moderation.service';
import { NotificationService } from '../notifications/notification.service';

class DraftPostDto {
  @IsOptional()
  @IsString()
  content?: string;
}

class UpdatePostDto {
  @IsString()
  @MinLength(1)
  content!: string;
}

class CreateCommentDto {
  @IsString()
  @MinLength(1)
  @MaxLength(500)
  content!: string;

  @IsOptional()
  @IsString()
  parentCommentId?: string;
}

@Controller('posts')
@UseGuards(JwtAuthGuard)
// 【缺陷9 修复】posts 限流：每分钟 20 次
@Throttle({ default: { limit: 20, ttl: 60_000 } })
export class PostsController {
  constructor(
    private readonly prisma: PrismaService,
    private readonly queue: QueueService,
    private readonly audit: AuditService,
    private readonly moderation: ModerationService,
    private readonly notifications: NotificationService,
  ) {}

  @Post('draft')
  async enqueueDraft(@CurrentUser() userId: string, @Body() dto: DraftPostDto) {
    const clone = await this.prisma.digitalClone.findUnique({ where: { userId } });
    if (!clone) return { queued: false, reason: 'no_clone' };

    // 入队和审计在后台执行，不阻塞前端响应
    this.queue
      .enqueuePostDraft({
        cloneId: clone.id,
        content: dto.content,
        trigger: 'manual',
      })
      .then(() =>
        this.audit.log({
          userId,
          eventType: 'post_drafted',
          summaryZh: `提交帖子草稿（clone=${clone.id}）`,
          referenceId: clone.id,
        }),
      )
      .catch((err) => {
        // 静默处理：不影响用户体验，生产环境可接入告警
        console.warn('[PostsController] enqueue/audit failed:', err?.message ?? err);
      });

    return { queued: true };
  }

  /**
   * PUT /posts/:id — 编辑当前用户分身的某条帖子内容。
   * 校验：帖子 cloneId 必须属于当前用户的 clone（防越权编辑他人帖子）。
   * 返回与 GET /clones/me/posts 一致的结构，前端可直接替换列表项。
   */
  @Put(':id')
  async updatePost(
    @CurrentUser() userId: string,
    @Param('id') postId: string,
    @Body() dto: UpdatePostDto,
  ) {
    const content = dto.content.trim();
    if (!content) {
      throw new BadRequestException('内容不能为空');
    }

    const clone = await this.prisma.digitalClone.findUnique({ where: { userId } });
    if (!clone) {
      throw new NotFoundException('尚未创建分身');
    }

    const post = await this.prisma.post.findUnique({
      where: { id: postId },
      select: { cloneId: true, createdAt: true, isAutoGenerated: true },
    });
    if (!post) {
      throw new NotFoundException('帖子不存在');
    }
    if (post.cloneId !== clone.id) {
      throw new ForbiddenException('无权编辑此帖子');
    }

    const updated = await this.prisma.post.update({
      where: { id: postId },
      data: { content, editedAt: new Date() },
      select: { id: true, content: true, createdAt: true, isAutoGenerated: true, editedAt: true },
    });

    // 审计日志异步执行，不阻塞响应
    this.audit
      .log({
        userId,
        eventType: 'post_updated',
        summaryZh: `编辑帖子（post=${postId}）`,
        referenceId: clone.id,
      })
      .catch((err) => {
        console.warn('[PostsController] audit failed:', err?.message ?? err);
      });

    return {
      id: updated.id,
      content: updated.content,
      createdAt: updated.createdAt,
      isAutoGenerated: updated.isAutoGenerated,
      editedAt: updated.editedAt,
    };
  }

  /**
   * DELETE /posts/:id — 删除当前用户分身的某条帖子。
   * 校验：帖子 cloneId 必须属于当前用户的 clone（防越权删除他人帖子）。
   */
  @Delete(':id')
  async deletePost(
    @CurrentUser() userId: string,
    @Param('id') postId: string,
  ) {
    const clone = await this.prisma.digitalClone.findUnique({ where: { userId } });
    if (!clone) {
      throw new NotFoundException('尚未创建分身');
    }

    const post = await this.prisma.post.findUnique({
      where: { id: postId },
      select: { cloneId: true },
    });
    if (!post) {
      throw new NotFoundException('帖子不存在');
    }
    if (post.cloneId !== clone.id) {
      throw new ForbiddenException('无权删除此帖子');
    }

    await this.prisma.post.delete({ where: { id: postId } });

    // 审计日志异步执行，不阻塞响应
    this.audit
      .log({
        userId,
        eventType: 'post_deleted',
        summaryZh: `删除帖子（post=${postId}）`,
        referenceId: clone.id,
      })
      .catch((err) => {
        console.warn('[PostsController] audit failed:', err?.message ?? err);
      });

    return { deleted: true };
  }

  /**
   * POST /posts/:id/comments — 对某条帖子发表评论。
   * 同步审核：先过敏感词正则，再过 DeepSeek LLM 分类。
   * - safe → 立即创建 Comment，立即可见
   * - unsafe → 400 拒绝（含原因）
   * - needs_review → 400 拒绝，提示修改后重试
   * 校验：登录 + 当前用户有 clone + 帖子存在。
   */
  @Post(':id/comments')
  async addComment(
    @CurrentUser() userId: string,
    @Param('id') postId: string,
    @Body() dto: CreateCommentDto,
  ) {
    const content = dto.content.trim();
    if (!content) {
      throw new BadRequestException('评论内容不能为空');
    }

    const clone = await this.prisma.digitalClone.findUnique({ where: { userId } });
    if (!clone) {
      throw new NotFoundException('尚未创建分身');
    }

    const post = await this.prisma.post.findUnique({
      where: { id: postId },
      select: { id: true },
    });
    if (!post) {
      throw new NotFoundException('帖子不存在');
    }

    // 校验父评论（如果指定了 parentCommentId）
    if (dto.parentCommentId) {
      const parentComment = await this.prisma.comment.findUnique({
        where: { id: dto.parentCommentId },
        select: { postId: true },
      });
      if (!parentComment || parentComment.postId !== postId) {
        throw new BadRequestException('父评论不存在');
      }
    }

    // 同步内容审核：敏感词 + DeepSeek LLM 分类
    const moderationResult = await this.moderation.moderate(content);
    if (moderationResult.verdict === 'unsafe') {
      throw new BadRequestException(
        `评论内容不合规：${moderationResult.reason ?? '请修改后重试'}`,
      );
    }
    if (moderationResult.verdict === 'needs_review') {
      throw new BadRequestException('评论内容需人工审核，请修改后再试');
    }

    const comment = await this.prisma.comment.create({
      data: {
        postId,
        cloneId: clone.id,
        content,
        ...(dto.parentCommentId ? { parentId: dto.parentCommentId } : {}),
      },
      include: {
        clone: { include: { user: { include: { profile: true } } } },
      },
    });

    // 审计日志异步执行，不阻塞响应
    this.audit
      .log({
        userId,
        eventType: 'comment_created',
        summaryZh: `评论帖子（post=${postId}, comment=${comment.id}${dto.parentCommentId ? `, parent=${dto.parentCommentId}` : ''}）`,
        referenceId: clone.id,
      })
      .catch((err) => {
        console.warn('[PostsController] audit failed:', err?.message ?? err);
      });

    // 发送通知（异步，不阻塞响应）
    const commenterName = comment.clone.user.profile?.displayName ?? '某位用户';
    const contentPreview = content.length > 30 ? `${content.slice(0, 30)}…` : content;

    this.notifyCommentRelatedUsers({
      postId,
      commenterId: userId,
      commenterName,
      contentPreview,
      commentContent: content,
      commentId: comment.id,
      parentCommentId: dto.parentCommentId,
    }).catch((err) => {
      console.warn('[PostsController] notification failed:', err?.message ?? err);
    });

    return {
      id: comment.id,
      content: comment.content,
      author: comment.clone.user.profile?.displayName ?? '分身',
      author_avatar: comment.clone.user.profile?.avatarUrl ?? null,
      created_at: comment.createdAt.toISOString(),
      parent_id: comment.parentId ?? null,
      clone_id: comment.cloneId,
    };
  }

  /**
   * 异步通知帖子相关用户：
   * 1. 帖子作者 → comment 通知
   * 2. 之前评论过的用户 → reply 通知（排除当前评论者）
   */
  private async notifyCommentRelatedUsers(opts: {
    postId: string;
    commenterId: string;
    commenterName: string;
    contentPreview: string;
    commentContent: string;
    commentId: string;
    parentCommentId?: string;
  }) {
    const { postId, commenterId, commenterName, contentPreview, commentContent, commentId, parentCommentId } = opts;

    const notifiedUserIds = new Set<string>();
    notifiedUserIds.add(commenterId); // 不通知自己

    if (parentCommentId) {
      // 回复某条评论：通知被回复的评论作者。
      // 使用 comment_reply 类型 + metadata（携带新评论内容与被引用的原评论），
      // 前端据此渲染 B 站风格的"回复了我的评论"卡片。
      const parentComment = await this.prisma.comment.findUnique({
        where: { id: parentCommentId },
        select: {
          content: true,
          clone: { select: { userId: true } },
        },
      });
      if (parentComment && !notifiedUserIds.has(parentComment.clone.userId)) {
        const replyPreview =
          commentContent.length > 120 ? `${commentContent.slice(0, 120)}…` : commentContent;
        const quotedPreview =
          parentComment.content.length > 160
            ? `${parentComment.content.slice(0, 160)}…`
            : parentComment.content;
        await this.notifications.create({
          userId: parentComment.clone.userId,
          type: 'comment_reply',
          title: commenterName,
          body: '回复了我的评论',
          refType: 'comment',
          refId: parentCommentId,
          fromUserId: commenterId,
          metadata: {
            actorName: commenterName,
            replyContent: replyPreview,
            quotedComment: { content: quotedPreview },
            postId,
            commentId,
            parentCommentId,
          },
        });
        notifiedUserIds.add(parentComment.clone.userId);
      }

      // 也通知帖子作者（如果不同于评论者和被回复者）
      const post = await this.prisma.post.findUnique({
        where: { id: postId },
        select: { clone: { select: { userId: true } } },
      });
      if (post && !notifiedUserIds.has(post.clone.userId)) {
        await this.notifications.create({
          userId: post.clone.userId,
          type: 'comment',
          title: '新评论',
          body: `${commenterName} 评论了你的帖子："${contentPreview}"`,
          refType: 'post',
          refId: postId,
          fromUserId: commenterId,
        });
        notifiedUserIds.add(post.clone.userId);
      }
    } else {
      // 顶层评论：通知帖子作者
      const post = await this.prisma.post.findUnique({
        where: { id: postId },
        select: { clone: { select: { userId: true } } },
      });

      if (post && post.clone.userId !== commenterId) {
        await this.notifications.create({
          userId: post.clone.userId,
          type: 'comment',
          title: '新评论',
          body: `${commenterName} 评论了你的帖子："${contentPreview}"`,
          refType: 'post',
          refId: postId,
          fromUserId: commenterId,
        });
        notifiedUserIds.add(post.clone.userId);
      }

      // 通知之前评论过的用户（去重），排除当前评论者和帖子作者
      const previousComments = await this.prisma.comment.findMany({
        where: { postId },
        select: { clone: { select: { userId: true } } },
      });

      for (const c of previousComments) {
        if (notifiedUserIds.has(c.clone.userId)) continue;
        notifiedUserIds.add(c.clone.userId);
        await this.notifications.create({
          userId: c.clone.userId,
          type: 'reply',
          title: '新回复',
          body: `${commenterName} 在你评论过的帖子下发表了评论："${contentPreview}"`,
          refType: 'post',
          refId: postId,
          fromUserId: commenterId,
        });
      }
    }
  }
}
