-- AddColumn: is_auto_generated（专用列，替代 metadata_json 内的同名字段）
ALTER TABLE "posts" ADD COLUMN "is_auto_generated" BOOLEAN NOT NULL DEFAULT false;

-- AddColumn: edited_at（用户手动编辑时间，NULL 表示从未编辑）
ALTER TABLE "posts" ADD COLUMN "edited_at" TIMESTAMP(3);

-- Backfill: 从 metadata_json 回填 is_auto_generated，保证历史数据与新列语义一致。
-- 优先取显式 isAutoGenerated 布尔；缺失时按 trigger !== 'manual' 推断；其余保持默认 false。
UPDATE "posts"
SET "is_auto_generated" = COALESCE(
  (metadata_json->>'isAutoGenerated')::boolean,
  (metadata_json->>'trigger' IS NOT NULL AND metadata_json->>'trigger' <> 'manual')
)
WHERE metadata_json IS NOT NULL;
