import { CloneStatus, PrismaClient } from '@prisma/client';
import { Queue } from 'bullmq';
import type Redis from 'ioredis';
import { chat } from './llm';
import { formatBoundariesClause } from './boundaries';
import { getCloneMeta } from './meta';
// 【缺陷2修复】引入 composeSystemPrompt，发帖场景也走 composer 统一组装 system prompt
import { composeSystemPrompt } from '../agent-platform/composer/prompt-composer';

const IDLE_MS = Number(process.env.CLONE_IDLE_POST_HOURS ?? 24) * 60 * 60 * 1000;

export async function generatePostContent(
  prisma: PrismaClient,
  cloneId: string,
  trigger: string,
  context: Record<string, unknown> = {},
): Promise<string | null> {
  const clone = await prisma.digitalClone.findUnique({
    where: { id: cloneId },
    include: { personaPrompt: true, user: { include: { profile: true } } },
  });
  const persona = clone?.personaPrompt?.promptText ?? '友好真诚的分身';
  const name = clone?.user.profile?.displayName ?? '分身';
  const boundaryClause = formatBoundariesClause(clone?.personaPrompt?.boundariesJson);

  // 【缺陷2修复】改用 composeSystemPrompt() 组装 system prompt（与 agent-turn 一致），
  // safety/skill 层和 boundary 信息通过 composer 的 L1 安全层注入，不再手动拼接。
  const systemPrompt = composeSystemPrompt({ persona, boundaryClause });

  // 72h 上下文发帖：若 context.recentMessages 存在，格式化为对话片段注入 user prompt，
  // 让 LLM 参考最近聊天生成更贴合心境的动态；普通 idle/manual 走原有逻辑。
  const recentMessages = Array.isArray(context.recentMessages) ? context.recentMessages : [];
  const recentChat = recentMessages
    .map((m: Record<string, unknown>, i: number) => {
      const speaker = typeof m?.speaker === 'string' ? m.speaker : '?';
      const content = typeof m?.content === 'string' ? m.content : '';
      return `${i + 1}. ${speaker}：${content}`;
    })
    .join('\n');
  const chatBlock = recentChat
    ? `\n\n以下是你最近的对话片段（可参考心境，但不要直接引用或复述）：\n${recentChat}`
    : '';
  const idleHint = trigger === 'idle_72h' ? '已经很久没有发广场动态了，' : '';

  // 【缺陷2修复】user prompt 保留发帖场景的指令；chat() 返回 string | null，直接透传。
  // 注意：不再把整个 context JSON.stringify 进 prompt（避免泄露无关字段），只透传 trigger 与对话片段。
  const userPrompt = `你是 ${name} 的数字分身。${idleHint}根据上述 persona 用中文写一条广场动态（80字内），语气一致，像你本人随手发的状态。触发原因：${trigger}。${chatBlock}`;
  return chat([
    { role: 'system', content: systemPrompt },
    { role: 'user', content: userPrompt },
  ]);
}

export async function runCloneRuntimeTick(
  prisma: PrismaClient,
  redis: Redis,
  connection: Redis,
  postDraftQueue: Queue,
): Promise<void> {
  const clones = await prisma.digitalClone.findMany({
    where: { status: CloneStatus.active },
  });
  const now = Date.now();

  for (const clone of clones) {
    const meta = await getCloneMeta(redis, clone.id);
    const lastActivity = Math.max(meta.lastPostAt, meta.lastSessionAt);
    if (lastActivity > 0 && now - lastActivity < IDLE_MS) continue;

    await postDraftQueue.add('draft', {
      cloneId: clone.id,
      content: '',
      trigger: 'idle',
      context: { idleHours: IDLE_MS / 3600000 },
    });
    console.log('[T_idle_post] queued for clone', clone.id);
  }
}

export async function enqueueAffinityPost(
  prisma: PrismaClient,
  connection: Redis,
  cloneId: string,
  sessionId: string,
  score: number,
  peerName: string,
  postDraftQueue: Queue,
): Promise<void> {
  await postDraftQueue.add('draft', {
    cloneId,
    content: '',
    trigger: 'affinity_boost',
    context: { sessionId, score, peerName },
  });
  console.log('[T_affinity_post] clone', cloneId, 'score', score);
}

/**
 * 72 小时空闲发帖巡检（每小时调用一次）。
 *
 * 触发条件（满足任一）：
 *   - clone 从未发过帖；或
 *   - 最近一条帖子的 createdAt 距今 > 72 小时。
 *
 * 触发后：
 *   1. 拉取该 clone 最近一次 AgentSession 的最近 5 条消息作为上下文（无会话则空数组）；
 *   2. 入队 post-draft（trigger='idle_72h'），由 post-draft worker 调用 LLM 生成内容、
 *      写库（isAutoGenerated=true）并经 moderation 队列审核发布；
 *   3. Redis clone:meta:{id}.lastPostAt 在帖子审核通过时由 moderation worker 更新，
 *      此处不重复写入，避免未审核就刷新时间戳导致误判。
 *
 * 与现有 24h runCloneRuntimeTick 的关系：后者每 15min 跑、阈值 24h、仅传 idleHours 上下文；
 * 本任务每 1h 跑、阈值 72h、附带最近聊天上下文，作为"长时间沉寂 + 上下文发帖"的兜底。
 * 若 24h tick 正常工作，帖子会持续更新，本任务通常不触发；仅当 24h tick 连续失败
 * （LLM 返回 null、审核拒绝等）超过 72h 时，本任务以更丰富上下文兜底发帖。
 */
export async function runIdlePostCheck72h(
  prisma: PrismaClient,
  postDraftQueue: Queue,
): Promise<void> {
  const SEVENTY_TWO_HOURS_MS = 72 * 60 * 60 * 1000;
  const clones = await prisma.digitalClone.findMany({
    where: { status: CloneStatus.active },
    select: { id: true },
  });
  const now = Date.now();
  let queued = 0;

  for (const clone of clones) {
    const latestPost = await prisma.post.findFirst({
      where: { cloneId: clone.id },
      orderBy: { createdAt: 'desc' },
      select: { createdAt: true },
    });

    const noPost = !latestPost;
    const stale = !!latestPost && now - latestPost.createdAt.getTime() > SEVENTY_TWO_HOURS_MS;
    if (!noPost && !stale) continue;

    // 拉取该 clone 最近的 AgentSession，取最近 5 条消息作为发帖上下文
    const recentSession = await prisma.agentSession.findFirst({
      where: { OR: [{ cloneAId: clone.id }, { cloneBId: clone.id }] },
      orderBy: { startedAt: 'desc' },
      select: { id: true },
    });

    let recentMessages: { speaker: string; content: string }[] = [];
    if (recentSession) {
      const msgs = await prisma.agentMessage.findMany({
        where: { sessionId: recentSession.id },
        orderBy: { createdAt: 'desc' },
        take: 5,
        select: { speakerCloneId: true, content: true },
      });
      // reverse 回时间正序，speaker 映射为"我/对方"避免泄露 clone id
      recentMessages = msgs.reverse().map((m) => ({
        speaker: m.speakerCloneId === clone.id ? '我' : '对方',
        content: m.content,
      }));
    }

    await postDraftQueue.add('draft', {
      cloneId: clone.id,
      content: '',
      trigger: 'idle_72h',
      context: { recentMessages, idleHours: 72 },
    });
    queued++;
    console.log('[T_idle_72h_post] queued for clone', clone.id, noPost ? '(no post)' : '(stale>72h)');
  }

  if (queued > 0) {
    console.log('[T_idle_72h_post] scan complete, queued', queued, 'of', clones.length, 'active clones');
  }
}
