import { BadRequestException, Injectable, NotFoundException } from '@nestjs/common';
import { CloneStatus, Prisma } from '@prisma/client';
import { PrismaService } from '../prisma/prisma.service';
import { AuditService } from '../audit/audit.service';
import { RedisService } from '../redis/redis.service';
import {
  CloneBoundariesDto,
  mergeBoundariesJson,
  parseBoundariesJson,
} from './clone-boundaries';
import type {
  IdealPartnerSketch,
  OnboardingSurveyJson,
  ScenarioResponse,
} from '../onboarding/survey-schema';
import { getCardDefinition } from '../onboarding/scenario-cards';
import {
  IDEAL_PARTNER_CARD_IDS,
  calculateIdealPartnerDimensions,
  toSurveyIdealPartnerDimensions,
} from '../onboarding/dimension-scorer';
import { IdealPartnerSketchService } from '../onboarding/ideal-partner-sketch.service';
import { LlmService } from '../llm/llm.service';
import { buildTextForIdealEmbedding } from '../onboarding/survey-schema';

// ---------- Response types ----------

/** personaSketch 子结构（从 bioJson.personaSketch 提取，含 narrative + 7 段 sections） */
type PersonaSketchResponse = {
  narrative: string;
  sections: {
    identityNarrative: string;
    personalityTexture: string;
    coreBeliefs: string;
    valuesInAction: string;
    caringStyle: string;
    socialBoundaries: string;
    contradictions: string;
    voiceAnchors: string[];
  };
};

/** GET /clones/me/posts 单条帖子返回结构 */
export interface MyPostDto {
  id: string;
  content: string;
  createdAt: Date;
  /** 是否自动生成（专用列，trigger !== 'manual' 即 true） */
  isAutoGenerated: boolean;
  /** 用户手动编辑时间；null 表示从未被编辑 */
  editedAt: Date | null;
}

/** personaSketch section key → 中文标题映射（与 persona-sketch.service.ts 解析标题保持一致） */
const PERSONA_SECTION_TITLES: { key: string; title: string }[] = [
  { key: 'identityNarrative', title: '身份脉络' },
  { key: 'personalityTexture', title: '性格底色' },
  { key: 'coreBeliefs', title: '核心信念' },
  { key: 'valuesInAction', title: '价值观优先级' },
  { key: 'caringStyle', title: '关心方式' },
  { key: 'socialBoundaries', title: '社交边界' },
  { key: 'contradictions', title: '内在矛盾' },
];

/** GET /clones/me 返回的 personaSketch section 单项（数组化，便于前端渲染） */
export interface PersonaSketchSectionItem {
  key: string;
  title: string;
  narrative: string;
}

/** GET /clones/me 返回的 scenarioCard 单项（补 scenarioText，前端无需维护 cardId→text 映射） */
export interface ScenarioCardWithText {
  cardId: string;
  scenarioText: string;
  choice: 'A' | 'B' | 'C' | 'D' | 'custom';
  freeText?: string;
}

@Injectable()
export class ClonesService {
  constructor(
    private readonly prisma: PrismaService,
    private readonly audit: AuditService,
    private readonly redis: RedisService,
    private readonly idealPartnerSketch: IdealPartnerSketchService,
    private readonly llm: LlmService,
  ) {}

  async getMe(userId: string) {
    const clone = await this.prisma.digitalClone.findUnique({
      where: { userId },
      include: { personaPrompt: true },
    });
    if (!clone) throw new NotFoundException('Clone not found');

    // 修复点：社交统计改为分项返回，避免 post+comment+like+session 混算。
    // - postCount / commentCount: 直接 count
    // - matchCount: AgentSession 中"对方 clone 不同于自己"的唯一匹配数
    //   理由：同一对 (A,B) 可能有多条 session，但只算一次匹配关系（去重，等同 partnerSet.size）。
    // - 保留 interactionCount 以向后兼容旧前端读取。
    const [postCount, commentCount, likeCount, sessionCount, sessions, profile] = await Promise.all([
      this.prisma.post.count({ where: { cloneId: clone.id } }),
      this.prisma.comment.count({ where: { cloneId: clone.id } }),
      this.prisma.like.count({ where: { cloneId: clone.id } }),
      this.prisma.agentSession.count({
        where: { OR: [{ cloneAId: clone.id }, { cloneBId: clone.id }] },
      }),
      this.prisma.agentSession.findMany({
        where: {
          OR: [{ cloneAId: clone.id }, { cloneBId: clone.id }],
          // 防御性过滤：排除 cloneA === cloneB 的自匹配 session
          NOT: {
            AND: [{ cloneAId: clone.id }, { cloneBId: clone.id }],
          },
        },
        select: { cloneAId: true, cloneBId: true },
      }),
      // ★ 新增：并行查询 Profile 以获取 gender / bioJson / matchPrefsJson
      this.prisma.profile.findUnique({
        where: { userId },
        select: { gender: true, bioJson: true, matchPrefsJson: true },
      }),
    ]);

    // 去重：把 (A,B) 与 (B,A) 视为同一对匹配关系，统计不同的对方 clone 数
    const partnerSet = new Set<string>();
    for (const s of sessions) {
      const partner = s.cloneAId === clone.id ? s.cloneBId : s.cloneAId;
      if (partner !== clone.id) partnerSet.add(partner);
    }
    const matchCount = partnerSet.size;

    // ★ 从 Redis clone:meta:{cloneId} 读取 lastPostAt。
    // 双重防护：
    //   (1) BYPASS_REDIS=true 时 createRedisClient 的 retryStrategy:null 让 hget 快速 reject；
    //   (2) 这里再加 2s 超时兜底，防止非 BYPASS 模式下 Upstash 抖动导致 getMe 永久挂死
    //       （ioredis maxRetriesPerRequest:null + 默认重试会让命令永不 reject，try/catch 等不到）。
    let lastPostAt: string | null = null;
    try {
      const raw = await Promise.race([
        this.redis.client.hget(`clone:meta:${clone.id}`, 'lastPostAt'),
        new Promise<null>((resolve) => setTimeout(() => resolve(null), 2000)),
      ]);
      if (raw) {
        const ts = Number(raw);
        if (ts > 0) lastPostAt = new Date(ts).toISOString();
      }
    } catch {
      // Redis 不可用时静默降级
    }

    // ★ 新增：从 bioJson 解析 scenarioCards（前 8 张）、personaSketch、idealPartnerSketch
    const bio = (typeof profile?.bioJson === 'object' && profile?.bioJson !== null
      ? (profile.bioJson as Record<string, unknown>)
      : {}) as Partial<OnboardingSurveyJson>;

    const scenarioCards: ScenarioResponse[] | null =
      Array.isArray(bio.scenarioCards) && bio.scenarioCards.length > 0
        ? bio.scenarioCards.slice(0, 8)
        : null;

    const personaSketch: PersonaSketchResponse | null =
      bio.personaSketch?.narrative && bio.personaSketch.sections
        ? {
            narrative: bio.personaSketch.narrative,
            sections: bio.personaSketch.sections,
          }
        : null;

    const idealPartnerSketch: IdealPartnerSketch | null =
      bio.idealPartnerSketch?.narrative && bio.idealPartnerSketch.dimensions
        ? bio.idealPartnerSketch
        : null;

    // ★ 对齐前端：scenarioCards 补 scenarioText（用 getCardDefinition 查表，前端无需维护映射）
    const scenarioCardsWithText: ScenarioCardWithText[] | null = scenarioCards
      ? scenarioCards.map((r) => {
          const def = getCardDefinition(r.cardId);
          return {
            cardId: r.cardId,
            scenarioText: def?.scenarioText ?? '',
            choice: r.choice,
            freeText: typeof r.freeText === 'string' && r.freeText.trim() ? r.freeText : undefined,
          };
        })
      : null;

    // ★ 对齐前端：personaSketch.sections(object) → personaSketchSections([{key,title,narrative}])
    const personaSketchSections: PersonaSketchSectionItem[] | null = personaSketch
      ? PERSONA_SECTION_TITLES.map(({ key, title }) => {
          const narrative = (personaSketch.sections as Record<string, unknown> | undefined)?.[key];
          return typeof narrative === 'string' && narrative.trim()
            ? { key, title, narrative: narrative.trim() }
            : null;
        }).filter((x): x is PersonaSketchSectionItem => x !== null)
      : null;

    // ★ 对齐前端：idealPartnerSketch.narrative → idealPartnerNarrative(string)
    const idealPartnerNarrative: string | null =
      typeof idealPartnerSketch?.narrative === 'string' && idealPartnerSketch.narrative.trim()
        ? idealPartnerSketch.narrative.trim()
        : null;

    // ★ 新增：3 道理想伴侣探测卡（unexpected_breakfast/silent_night/song_choice）是否已答
    // 前端据此决定 CTA：已答→"生成理想型描述"直接 generate；未答→"补做3道问卷"先答题
    const idealPartnerCardsAnswered = this.checkIdealPartnerCardsAnswered(bio.scenarioCards);

    // ★ 新增：从 matchPrefsJson 提取 relationshipIntent
    const matchPrefs = (typeof profile?.matchPrefsJson === 'object' && profile?.matchPrefsJson !== null
      ? (profile.matchPrefsJson as Record<string, unknown>)
      : {});
    const relationshipIntent: string | null =
      typeof matchPrefs.relationshipIntent === 'string' && matchPrefs.relationshipIntent.trim()
        ? matchPrefs.relationshipIntent.trim()
        : null;

    return {
      id: clone.id,
      status: clone.status,
      consentAt: clone.consentAt,
      persona: clone.personaPrompt?.promptText ?? null,
      boundaries: clone.personaPrompt
        ? (parseBoundariesJson(clone.personaPrompt.boundariesJson) ?? {
            forbiddenWords: [],
            topicsToAvoid: null,
          })
        : null,
      // 旧字段：post + comment + like + session 混算（向后兼容保留）
      interactionCount: postCount + commentCount + likeCount + sessionCount,
      // 新字段：分项统计，前端可分别展示 post / comment / match 三类
      socialStats: {
        postCount,
        commentCount,
        matchCount,
      },
      // ★ 新增字段（全部 optional，向后兼容）
      relationshipIntent,
      // scenarioCards 已补 scenarioText（前端直接渲染，无需维护 cardId→text 映射）
      scenarioCards: scenarioCardsWithText,
      // personaSketch 旧结构保留（向后兼容）；新增数组化 sections 供前端渲染
      personaSketch,
      personaSketchSections,
      // idealPartnerSketch 旧结构保留；新增纯 narrative 供前端展示
      idealPartnerSketch,
      idealPartnerNarrative,
      // ★ 新增：3 道理想型探测卡答题状态（前端 CTA 判断用）
      idealPartnerCardsAnswered,
      gender: profile?.gender ?? null,
      lastPostAt,
    };
  }

  /**
   * GET /clones/me/posts — 返回当前 clone 的所有帖子，按 createdAt 倒序。
   * isAutoGenerated 与 editedAt 直接读取专用列（迁移 20260708000000 后已回填），
   * 不再从 metadataJson 解析，避免双源不一致。
   */
  async getMyPosts(userId: string): Promise<MyPostDto[]> {
    const clone = await this.prisma.digitalClone.findUnique({
      where: { userId },
      select: { id: true },
    });
    if (!clone) throw new NotFoundException('Clone not found');

    const posts = await this.prisma.post.findMany({
      where: { cloneId: clone.id },
      orderBy: { createdAt: 'desc' },
      select: { id: true, content: true, createdAt: true, isAutoGenerated: true, editedAt: true },
    });

    return posts.map((p) => ({
      id: p.id,
      content: p.content,
      createdAt: p.createdAt,
      isAutoGenerated: p.isAutoGenerated,
      editedAt: p.editedAt,
    }));
  }

  /**
   * PUT /clones/me/persona-sketch — 编辑人格画像 sections，持久化到 Profile.bioJson.personaSketch.sections。
   * 仅允许更新 7 个已知 key（PERSONA_SECTION_TITLES 白名单），保留 narrative / voiceAnchors 不变。
   * personaSketch 不存在时拒绝（要求先完成入驻生成画像），避免凭空创建结构。
   */
  async updatePersonaSketch(
    userId: string,
    sections: { key: string; narrative: string }[],
  ) {
    const profile = await this.prisma.profile.findUnique({
      where: { userId },
      select: { bioJson: true },
    });
    if (!profile) {
      throw new NotFoundException('用户档案不存在');
    }

    const bio =
      typeof profile.bioJson === 'object' && profile.bioJson !== null
        ? { ...(profile.bioJson as Record<string, unknown>) }
        : ({} as Record<string, unknown>);

    const personaSketch =
      typeof bio.personaSketch === 'object' && bio.personaSketch !== null
        ? { ...(bio.personaSketch as Record<string, unknown>) }
        : null;

    if (!personaSketch) {
      throw new BadRequestException('尚未生成人格画像，请先完成入驻问卷');
    }

    const existingSections =
      typeof personaSketch.sections === 'object' && personaSketch.sections !== null
        ? { ...(personaSketch.sections as Record<string, unknown>) }
        : {};

    // 白名单：只允许更新 7 个已知 key，避免写入任意字段污染 bioJson
    const allowedKeys = new Set(PERSONA_SECTION_TITLES.map((s) => s.key));
    for (const { key, narrative } of sections) {
      if (allowedKeys.has(key) && typeof narrative === 'string' && narrative.trim()) {
        existingSections[key] = narrative.trim();
      }
    }

    personaSketch.sections = existingSections;
    bio.personaSketch = personaSketch;

    await this.prisma.profile.update({
      where: { userId },
      data: { bioJson: bio as Prisma.InputJsonValue },
    });

    await this.audit.log({
      userId,
      eventType: 'clone.update',
      summaryZh: '编辑人格画像 sections',
    });

    return this.getMe(userId);
  }

  async updateMe(
    userId: string,
    data: { status?: CloneStatus; personaText?: string; boundaries?: CloneBoundariesDto },
  ) {
    let clone = await this.prisma.digitalClone.findUnique({
      where: { userId },
      include: { personaPrompt: true },
    });
    if (!clone) {
      clone = await this.prisma.digitalClone.create({
        data: { userId, status: data.status ?? CloneStatus.draft },
        include: { personaPrompt: true },
      });
    } else if (data.status) {
      clone = await this.prisma.digitalClone.update({
        where: { id: clone.id },
        data: { status: data.status },
        include: { personaPrompt: true },
      });
    }

    const needsPersonaUpsert =
      data.personaText !== undefined || data.boundaries !== undefined;

    if (needsPersonaUpsert) {
      const existingJson = clone.personaPrompt?.boundariesJson ?? null;
      const boundariesJson: Prisma.InputJsonValue = data.boundaries
        ? (mergeBoundariesJson(existingJson, data.boundaries) as Prisma.InputJsonValue)
        : ((existingJson ?? {
            handoff: true,
            forbiddenWords: [],
            topicsToAvoid: null,
          }) as Prisma.InputJsonValue);

      const promptText =
        data.personaText !== undefined
          ? data.personaText
          : (clone.personaPrompt?.promptText ?? '');

      await this.prisma.personaPrompt.upsert({
        where: { cloneId: clone.id },
        create: {
          cloneId: clone.id,
          promptText: promptText || ' ',
          boundariesJson,
        },
        update: {
          ...(data.personaText !== undefined
            ? { promptText: data.personaText, version: { increment: 1 } }
            : {}),
          ...(data.boundaries !== undefined ? { boundariesJson } : {}),
        },
      });
    }

    const summaryZh = data.boundaries
      ? '更新分身社交边界'
      : data.personaText
        ? '更新分身人格设定'
        : `更新分身状态：${clone.status}`;

    await this.audit.log({
      userId,
      cloneId: clone.id,
      eventType: 'clone.update',
      summaryZh,
    });
    return this.getMe(userId);
  }

  async pause(userId: string) {
    return this.updateMe(userId, { status: CloneStatus.paused });
  }

  async resume(userId: string) {
    return this.updateMe(userId, { status: CloneStatus.active });
  }

  // -----------------------------------------------------------------------
  // 理想型补做（已 finalize 用户，绕开 OnboardingSession.completed 限制）
  // -----------------------------------------------------------------------

  /**
   * 检查 3 道理想伴侣探测卡是否都已答（有 choice）。
   * 用于 getMe 返回 idealPartnerCardsAnswered，前端 CTA 判断：
   *   已答 → "生成理想型描述"直接 generate
   *   未答 → "补做 3 道问卷"先答题再 generate
   */
  private checkIdealPartnerCardsAnswered(
    scenarioCards: ScenarioResponse[] | null | undefined,
  ): boolean {
    if (!Array.isArray(scenarioCards) || scenarioCards.length === 0) return false;
    const answeredIds = new Set(
      scenarioCards
        .filter((c) => c && typeof c.cardId === 'string' && c.choice)
        .map((c) => c.cardId),
    );
    for (const id of IDEAL_PARTNER_CARD_IDS) {
      if (!answeredIds.has(id)) return false;
    }
    return true;
  }

  /**
   * POST /clones/me/ideal-partner/cards
   * 已 finalize 用户补答 3 道理想伴侣探测卡。
   * 合并写入 Profile.bioJson.scenarioCards（替换同 cardId 旧答案），
   * 重算 idealPartnerDimensions 写回 bioJson。
   * 不生成 idealPartnerSketch（由 generate 端点单独触发）。
   */
  async submitIdealPartnerCards(
    userId: string,
    cards: { cardId: string; choice: string; freeText?: string }[],
  ) {
    if (!Array.isArray(cards) || cards.length === 0) {
      throw new BadRequestException('卡片回答不能为空');
    }
    for (const c of cards) {
      if (!IDEAL_PARTNER_CARD_IDS.has(c.cardId)) {
        throw new BadRequestException(
          `非法卡片 ID "${c.cardId}"，只接受理想伴侣探测卡（unexpected_breakfast/silent_night/song_choice）`,
        );
      }
      if (!c.choice || typeof c.choice !== 'string') {
        throw new BadRequestException(`卡片 ${c.cardId} 缺少 choice`);
      }
    }

    const profile = await this.prisma.profile.findUnique({
      where: { userId },
      select: { bioJson: true },
    });
    if (!profile) {
      throw new NotFoundException('用户档案不存在');
    }

    const bio =
      typeof profile.bioJson === 'object' && profile.bioJson !== null
        ? { ...(profile.bioJson as Record<string, unknown>) }
        : ({} as Record<string, unknown>);

    // 合并 scenarioCards：保留非理想卡，替换 3 张理想卡
    const existingCards: ScenarioResponse[] = Array.isArray(bio.scenarioCards)
      ? (bio.scenarioCards as ScenarioResponse[])
      : [];
    const otherCards = existingCards.filter(
      (c) => !IDEAL_PARTNER_CARD_IDS.has(c.cardId),
    );
    const newResponses: ScenarioResponse[] = cards.map((c) => ({
      cardId: c.cardId,
      choice: c.choice as ScenarioResponse['choice'],
      freeText: typeof c.freeText === 'string' ? c.freeText : undefined,
    }));
    const mergedCards = [...otherCards, ...newResponses];

    // 重算理想伴侣维度（函数内部自动 filter 出 3 张理想卡）
    const idealDims = calculateIdealPartnerDimensions(mergedCards);
    const idealDimsJson = toSurveyIdealPartnerDimensions(idealDims);

    bio.scenarioCards = mergedCards;
    bio.idealPartnerDimensions = idealDimsJson;
    // 卡答案变了，旧 idealPartnerSketch 失效，需重新 generate
    if (bio.idealPartnerSketch) {
      delete bio.idealPartnerSketch;
    }

    await this.prisma.profile.update({
      where: { userId },
      data: { bioJson: bio as Prisma.InputJsonValue },
    });

    await this.audit.log({
      userId,
      eventType: 'clone.update',
      summaryZh: '补答理想伴侣探测卡（分身页）',
    });

    return this.getMe(userId);
  }

  /**
   * POST /clones/me/ideal-partner/generate
   * 已 finalize 用户从 Profile.bioJson 生成 idealPartnerSketch 叙事，
   * 写回 bioJson.idealPartnerSketch，并重算 ideal_embedding 写入 profile_embeddings 表。
   *
   * 前置：3 道理想伴侣探测卡已答（否则提示先调 cards 端点）。
   * 绕开 OnboardingSession.completed=false 限制，直接从 bioJson 读数据。
   * 复用 IdealPartnerSketchService.generateFromSurvey 纯合成逻辑。
   */
  async generateIdealPartner(userId: string) {
    const profile = await this.prisma.profile.findUnique({
      where: { userId },
      select: { bioJson: true },
    });
    if (!profile) {
      throw new NotFoundException('用户档案不存在');
    }

    const bio =
      typeof profile.bioJson === 'object' && profile.bioJson !== null
        ? (profile.bioJson as Record<string, unknown>)
        : {};

    const survey = bio as Partial<OnboardingSurveyJson>;

    // 前置校验：3 道理想卡必须已答
    if (!this.checkIdealPartnerCardsAnswered(survey.scenarioCards)) {
      throw new BadRequestException(
        '请先补答 3 道理想伴侣探测卡，再生成理想型描述',
      );
    }

    // 调复用的纯合成函数（不查 OnboardingSession）
    const sketch = await this.idealPartnerSketch.generateFromSurvey(
      survey as OnboardingSurveyJson,
    );

    // 写回 Profile.bioJson.idealPartnerSketch
    const updatedBio = { ...bio, idealPartnerSketch: sketch };
    await this.prisma.profile.update({
      where: { userId },
      data: { bioJson: updatedBio as unknown as Prisma.InputJsonValue },
    });

    // 重算 ideal_embedding 并 upsert（双向互匹配依赖此列）
    await this.reembedIdeal(userId, updatedBio as OnboardingSurveyJson, profile);

    await this.audit.log({
      userId,
      eventType: 'clone.update',
      summaryZh: '生成理想伴侣画像并重算 embedding（分身页）',
    });

    return this.getMe(userId);
  }

  /**
   * 重算 ideal_embedding 并 upsert 到 profile_embeddings 表。
   * 只更新 ideal_embedding 列，保留 self embedding 不变。
   * embed 质量为 fake 或向量无效时静默跳过（不阻断 sketch 写入，匹配侧降级）。
   */
  private async reembedIdeal(
    userId: string,
    survey: OnboardingSurveyJson,
    profile: { bioJson?: unknown } | null,
  ): Promise<void> {
    try {
      const text = buildTextForIdealEmbedding(profile, survey, userId);
      const { vector, quality } = await this.llm.embed(text);
      if (quality === 'fake') return;

      // 向量有效性校验：全 0 或方差过小跳过
      const mean = vector.reduce((a, b) => a + b, 0) / vector.length;
      const stddev = Math.sqrt(
        vector.reduce((s, v) => s + (v - mean) ** 2, 0) / vector.length,
      );
      if (vector.every((v) => v === 0) || stddev < 0.001) return;

      const vecStr = `[${vector.join(',')}]`;
      await this.prisma.$executeRaw`
        INSERT INTO profile_embeddings (user_id, ideal_embedding)
        VALUES (${userId}, ${vecStr}::vector)
        ON CONFLICT (user_id) DO UPDATE SET ideal_embedding = ${vecStr}::vector
      `;
    } catch {
      // embed / SQL 失败不阻断主流程：sketch 已写入，匹配侧降级
    }
  }
}
