/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { apiGetJson, apiPostJson, apiPutJson, getApiBaseUrl, unwrap } from './client';
import type { ApiResult } from './client';

export type CloneBoundaries = {
  forbiddenWords: string[];
  topicsToAvoid: string | null;
};

/** 场景卡片单项（后端已补 scenarioText，前端无需维护 cardId→text 映射） */
export type ScenarioCardItem = {
  cardId: string;
  scenarioText: string;
  choice: string;
  freeText?: string;
};

/** personaSketch section 单项（数组化，前端渲染用） */
export type PersonaSketchSection = {
  key: string;
  title: string;
  narrative: string;
};

/** 历史帖子单项 */
export type ClonePost = {
  id: string;
  content: string;
  createdAt: string;
  isAutoGenerated: boolean;
};

export type CloneSocialStats = {
  postCount: number;
  commentCount: number;
  matchCount: number;
};

export type CloneMe = {
  id: string;
  status: string;
  persona: string | null;
  boundaries: CloneBoundaries | null;
  /** 旧字段：post+comment+like+session 混算（向后兼容） */
  interactionCount: number;
  /** 新字段：分项统计 */
  socialStats: CloneSocialStats;
  /** 用户性别（male/female/...），前端用于选默认头像 */
  gender: string | null;
  /** 关系意图（恋爱/先交朋友/慢慢来/自我探索 等） */
  relationshipIntent: string | null;
  /** 情境卡片回答（前 8 张，已补 scenarioText） */
  scenarioCards: ScenarioCardItem[] | null;
  /** personaSketch sections 数组化（[{key,title,narrative}]） */
  personaSketchSections: PersonaSketchSection[] | null;
  /** 理想型自然语言描述 */
  idealPartnerNarrative: string | null;
  /** 3 道理想伴侣探测卡是否已答（前端 CTA 判断用） */
  idealPartnerCardsAnswered: boolean;
  /** 最近一次发帖时间（ISO string） */
  lastPostAt: string | null;
  /** 当前分身的历史帖子（loadCloneMe 时并行拉取；pause/resume/update 后保留为空数组） */
  posts: ClonePost[];
};

const EMPTY_BOUNDARIES: CloneBoundaries = { forbiddenWords: [], topicsToAvoid: null };
const EMPTY_SOCIAL_STATS: CloneSocialStats = { postCount: 0, commentCount: 0, matchCount: 0 };

function mapBoundaries(raw: unknown): CloneBoundaries {
  if (!raw || typeof raw !== 'object') return { ...EMPTY_BOUNDARIES };
  const o = raw as Record<string, unknown>;
  const forbiddenWords = Array.isArray(o.forbiddenWords)
    ? o.forbiddenWords.filter((x): x is string => typeof x === 'string').map((x) => x.trim()).filter(Boolean)
    : [];
  const topicsToAvoid =
    typeof o.topicsToAvoid === 'string' && o.topicsToAvoid.trim() ? o.topicsToAvoid.trim() : null;
  return { forbiddenWords: [...new Set(forbiddenWords)], topicsToAvoid };
}

function mapSocialStats(raw: unknown): CloneSocialStats {
  if (!raw || typeof raw !== 'object') return { ...EMPTY_SOCIAL_STATS };
  const o = raw as Record<string, unknown>;
  return {
    postCount: typeof o.postCount === 'number' ? o.postCount : 0,
    commentCount: typeof o.commentCount === 'number' ? o.commentCount : 0,
    matchCount: typeof o.matchCount === 'number' ? o.matchCount : 0,
  };
}

function mapScenarioCards(raw: unknown): ScenarioCardItem[] | null {
  if (!Array.isArray(raw) || raw.length === 0) return null;
  const out: ScenarioCardItem[] = [];
  for (const r of raw) {
    if (!r || typeof r !== 'object') continue;
    const o = r as Record<string, unknown>;
    const cardId = String(o.cardId ?? '');
    if (!cardId) continue;
    out.push({
      cardId,
      scenarioText: typeof o.scenarioText === 'string' ? o.scenarioText : '',
      choice: typeof o.choice === 'string' ? o.choice : '',
      freeText:
        typeof o.freeText === 'string' && o.freeText.trim() ? o.freeText : undefined,
    });
  }
  return out.length > 0 ? out : null;
}

function mapPersonaSketchSections(raw: unknown): PersonaSketchSection[] | null {
  if (!Array.isArray(raw) || raw.length === 0) return null;
  const out: PersonaSketchSection[] = [];
  for (const r of raw) {
    if (!r || typeof r !== 'object') continue;
    const o = r as Record<string, unknown>;
    const narrative = typeof o.narrative === 'string' ? o.narrative : '';
    if (!narrative.trim()) continue;
    out.push({
      key: String(o.key ?? ''),
      title: typeof o.title === 'string' ? o.title : '',
      narrative,
    });
  }
  return out.length > 0 ? out : null;
}

function mapPost(raw: unknown): ClonePost | null {
  if (!raw || typeof raw !== 'object') return null;
  const o = raw as Record<string, unknown>;
  const createdAtRaw = o.createdAt;
  const createdAt =
    typeof createdAtRaw === 'string'
      ? createdAtRaw
      : createdAtRaw instanceof Date
        ? createdAtRaw.toISOString()
        : '';
  return {
    id: String(o.id ?? ''),
    content: typeof o.content === 'string' ? o.content : '',
    createdAt,
    isAutoGenerated: typeof o.isAutoGenerated === 'boolean' ? o.isAutoGenerated : false,
  };
}

function mapPosts(raw: unknown): ClonePost[] {
  if (!Array.isArray(raw)) return [];
  return raw
    .map(mapPost)
    .filter((x): x is ClonePost => x !== null && Boolean(x.id));
}

function strOrNull(v: unknown): string | null {
  return typeof v === 'string' && v.trim() ? v : null;
}

function mapCloneMe(raw: Record<string, unknown>, posts: ClonePost[] = []): CloneMe {
  return {
    id: String(raw.id ?? ''),
    status: String(raw.status ?? ''),
    persona: typeof raw.persona === 'string' ? raw.persona : null,
    boundaries: raw.boundaries != null ? mapBoundaries(raw.boundaries) : null,
    interactionCount: typeof raw.interactionCount === 'number' ? raw.interactionCount : 0,
    socialStats: mapSocialStats(raw.socialStats),
    gender: strOrNull(raw.gender),
    relationshipIntent: strOrNull(raw.relationshipIntent),
    scenarioCards: mapScenarioCards(raw.scenarioCards),
    personaSketchSections: mapPersonaSketchSections(raw.personaSketchSections),
    idealPartnerNarrative: strOrNull(raw.idealPartnerNarrative),
    idealPartnerCardsAnswered:
      typeof raw.idealPartnerCardsAnswered === 'boolean' ? raw.idealPartnerCardsAnswered : false,
    lastPostAt: strOrNull(raw.lastPostAt),
    posts,
  };
}

/** Parse textarea: one word per line or comma-separated. */
export function parseForbiddenWordsInput(text: string): string[] {
  const parts = text.split(/[\n,，、]/);
  const seen = new Set<string>();
  const out: string[] = [];
  for (const raw of parts) {
    const w = raw.trim();
    if (!w || seen.has(w)) continue;
    seen.add(w);
    out.push(w);
  }
  return out;
}

export function forbiddenWordsToText(words: string[]): string {
  return words.join('\n');
}

/**
 * 加载分身数据：并行调用 /clones/me 和 /clones/me/posts。
 * posts 拉取失败时静默降级为空数组（不阻断主数据加载）。
 */
export async function loadCloneMe(): Promise<CloneMe | null> {
  if (!getApiBaseUrl()) return null;

  const [meRes, postsRes] = await Promise.allSettled([
    apiGetJson<Record<string, unknown>>('/clones/me'),
    apiGetJson<unknown[]>('/clones/me/posts'),
  ]);

  if (meRes.status !== 'fulfilled') {
    throw meRes.reason instanceof Error ? meRes.reason : new Error('clone load failed');
  }
  const meRaw = unwrap(meRes.value);
  if (!meRaw) return null;

  let posts: ClonePost[] = [];
  if (postsRes.status === 'fulfilled') {
    const postsRaw = unwrap(postsRes.value);
    posts = mapPosts(postsRaw);
  }

  return mapCloneMe(meRaw, posts);
}

export async function pauseClone(): Promise<CloneMe | null> {
  // 【缺陷5适配】apiPostJson 返回 ApiResult，用 unwrap 取 data
  const raw = unwrap(await apiPostJson<object, Record<string, unknown>>('/clones/me/pause', {}));
  return raw ? mapCloneMe(raw) : null;
}

export async function resumeClone(): Promise<CloneMe | null> {
  const raw = unwrap(await apiPostJson<object, Record<string, unknown>>('/clones/me/resume', {}));
  return raw ? mapCloneMe(raw) : null;
}

export async function updateClonePersona(personaText: string): Promise<CloneMe | null> {
  if (!getApiBaseUrl()) return null;
  const raw = unwrap(
    await apiPutJson<{ personaText: string }, Record<string, unknown>>('/clones/me', {
      personaText,
    }),
  );
  return raw ? mapCloneMe(raw) : null;
}

export async function updateCloneBoundaries(boundaries: CloneBoundaries): Promise<CloneMe | null> {
  if (!getApiBaseUrl()) return null;
  const raw = unwrap(
    await apiPutJson<
      { boundaries: { forbiddenWords: string[]; topicsToAvoid?: string | null } },
      Record<string, unknown>
    >('/clones/me', {
      boundaries: {
        forbiddenWords: boundaries.forbiddenWords,
        topicsToAvoid: boundaries.topicsToAvoid ?? undefined,
      },
    }),
  );
  return raw ? mapCloneMe(raw) : null;
}

/**
 * `PUT /clones/me/persona-sketch` — 编辑人格画像 sections，持久化到 bioJson.personaSketch.sections。
 * 后端按 7 个已知 key 白名单更新，personaSketch 不存在时返回 400。
 * @param sections [{key, narrative}]，key 须为 identityNarrative/personalityTexture/...
 * @returns 更新后的 CloneMe（含新 personaSketchSections），失败返回 null
 */
export async function updatePersonaSketch(
  sections: { key: string; narrative: string }[],
): Promise<CloneMe | null> {
  if (!getApiBaseUrl()) return null;
  const raw = unwrap(
    await apiPutJson<
      { sections: { key: string; narrative: string }[] },
      Record<string, unknown>
    >('/clones/me/persona-sketch', { sections }),
  );
  return raw ? mapCloneMe(raw) : null;
}

// ─── 理想型补做（已 finalize 用户，绕开 OnboardingSession 限制）─────────────

export type IdealPartnerCardInput = {
  cardId: string;
  choice: string;
  freeText?: string;
};

/**
 * POST /clones/me/ideal-partner/cards — 补答 3 道理想伴侣探测卡。
 * 合并答案到 Profile.bioJson + 重算 idealPartnerDimensions，不生成 sketch。
 * 返回 ApiResult 以便前端展示错误（如非法 cardId）。
 */
export async function submitIdealPartnerCards(
  cards: IdealPartnerCardInput[],
): Promise<ApiResult<CloneMe>> {
  if (!getApiBaseUrl()) return { ok: false, status: -1, message: 'no-base' };
  const result = await apiPostJson<
    { cards: IdealPartnerCardInput[] },
    Record<string, unknown>
  >('/clones/me/ideal-partner/cards', { cards });
  if (result.ok) {
    return { ok: true, data: mapCloneMe(result.data) };
  }
  return result as unknown as ApiResult<CloneMe>;
}

/**
 * POST /clones/me/ideal-partner/generate — 生成理想型描述 + 重算 ideal_embedding。
 * 前置：3 道探测卡已答（后端校验，未答返回 400 提示先补答）。
 * 返回 ApiResult 以便前端区分"未答卡"(400) / "LLM 不可用"(503) / 网络错误。
 */
export async function generateIdealPartnerClone(): Promise<ApiResult<CloneMe>> {
  if (!getApiBaseUrl()) return { ok: false, status: -1, message: 'no-base' };
  const result = await apiPostJson<Record<string, never>, Record<string, unknown>>(
    '/clones/me/ideal-partner/generate',
    {} as Record<string, never>,
  );
  if (result.ok) {
    return { ok: true, data: mapCloneMe(result.data) };
  }
  return result as unknown as ApiResult<CloneMe>;
}
