/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import type { Post } from '../types';
import type { ClonePost } from './clone';
import { apiGetJson, apiPostJson, apiPutJson, apiDeleteJson, getApiBaseUrl, unwrap } from './client';

export type PostDraftResult =
  | { ok: true; queued: true }
  | { ok: false; reason: 'no_api' | 'no_clone' | 'request_failed' };

type DraftResponse = { queued?: boolean; reason?: string };

/** `POST /posts/draft` — enqueue post-draft job (empty content → Worker LLM). */
export async function enqueuePostDraft(content?: string): Promise<PostDraftResult> {
  if (!getApiBaseUrl()) {
    return { ok: false, reason: 'no_api' };
  }

  const body = content?.trim() ? { content: content.trim() } : {};
  const ac = new AbortController();
  const timeoutId = setTimeout(() => ac.abort(), 10_000);
  try {
    const res = unwrap(
      await apiPostJson<typeof body, DraftResponse>('/posts/draft', body, ac.signal),
    );
    if (!res) {
      return { ok: false, reason: 'request_failed' };
    }
    if (res.queued === true) {
      return { ok: true, queued: true };
    }
    if (res.reason === 'no_clone') {
      return { ok: false, reason: 'no_clone' };
    }
    return { ok: false, reason: 'request_failed' };
  } finally {
    clearTimeout(timeoutId);
  }
}

function sleep(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

/** Poll feed refresh until a post id not in `previousIds` appears, or attempts exhausted. */
export async function pollFeedUntilNewPost(
  refresh: () => Promise<Post[]>,
  previousIds: Set<string>,
  opts?: { attempts?: number; intervalMs?: number },
): Promise<boolean> {
  const attempts = opts?.attempts ?? 8;
  const intervalMs = opts?.intervalMs ?? 1500;

  for (let i = 0; i < attempts; i++) {
    const next = await refresh();
    if (next.some((p) => !previousIds.has(p.id))) {
      return true;
    }
    if (i < attempts - 1) {
      await sleep(intervalMs);
    }
  }
  return false;
}

/** 把后端返回的任意对象映射为 ClonePost（容错：缺字段时降级）。 */
function mapPostRaw(r: unknown): ClonePost | null {
  if (!r || typeof r !== 'object') return null;
  const o = r as Record<string, unknown>;
  const c = o.createdAt;
  const createdAt =
    typeof c === 'string' ? c : c instanceof Date ? c.toISOString() : '';
  return {
    id: String(o.id ?? ''),
    content: typeof o.content === 'string' ? o.content : '',
    createdAt,
    isAutoGenerated: typeof o.isAutoGenerated === 'boolean' ? o.isAutoGenerated : false,
  };
}

/**
 * `GET /clones/me/posts` — 拉取当前分身的历史帖子（按 createdAt 倒序）。
 * 用于"我的分身"页历史帖子列表。失败或无 API 时返回空数组。
 */
export async function getMyPosts(): Promise<ClonePost[]> {
  if (!getApiBaseUrl()) return [];
  const raw = unwrap(await apiGetJson<unknown[]>('/clones/me/posts'));
  if (!Array.isArray(raw)) return [];
  return raw
    .map(mapPostRaw)
    .filter((x): x is ClonePost => x !== null && Boolean(x.id));
}

/**
 * `PUT /posts/:id` — 编辑当前分身某条帖子内容。
 * 后端校验归属（帖子 cloneId 必须属于当前用户的 clone），无权时返回 403。
 * @returns 更新后的帖子，失败返回 null
 */
export async function updatePost(postId: string, content: string): Promise<ClonePost | null> {
  if (!getApiBaseUrl()) return null;
  const raw = unwrap(
    await apiPutJson<{ content: string }, Record<string, unknown>>(
      `/posts/${encodeURIComponent(postId)}`,
      { content },
    ),
  );
  if (!raw) return null;
  return mapPostRaw(raw);
}

/**
 * `DELETE /posts/:id` — 删除当前分身的某条帖子。
 * 后端校验权限（帖子 cloneId 必须属于当前用户的 clone）。
 * @returns 是否删除成功
 */
export async function deletePost(postId: string): Promise<boolean> {
  if (!getApiBaseUrl()) return false;
  const result = await apiDeleteJson(`/posts/${encodeURIComponent(postId)}`);
  return result.ok;
}
